psa-token = {
    psa-nonce,
    psa-instance-id,
    psa-verification-service-indicator,
    psa-profile,
    psa-implementation-id,
    psa-client-id,
    psa-lifecycle,
    psa-certification-reference,
    psa-boot-seed,
    ( psa-software-components // psa-no-sw-measurement ),
}

psa-client-id-key = -4500
psa-lifecycle-key = -4501 
psa-implementation-id-key = -4502
psa-boot-seed-key = -4503
psa-certification-reference-key = -4504
psa-software-components-key = -4505
psa-no-sw-measurement-key = -4506
psa-verification-service-indicator-key = -4507

; from EAT
nonce-label = 10
ueid-label = 256
profile-label = 265
