psa-token = {
    psa-nonce,
    psa-instance-id,
    psa-verification-service-indicator,
    psa-profile,
    psa-implementation-id,
    psa-client-id,
    psa-lifecycle,
    psa-certification-reference,
    psa-boot-seed,
    ( psa-software-components // psa-no-sw-measurement ),
}

psa-client-id-key = 2394
psa-lifecycle-key = 2395
psa-implementation-id-key = 2396
psa-boot-seed-key = 2397
psa-certification-reference-key = 2398
psa-software-components-key = 2399
psa-no-sw-measurement-key = 2400
psa-verification-service-indicator-key = 2401

; from EAT
nonce-label = 10
ueid-label = 256
profile-label = 265
