psa-software-component = {
  ? 1 => text,          ; measurement type
    2 => psa-hash-type, ; measurement value
  ? 4 => text,          ; version
    5 => psa-hash-type, ; signer id
  ? 6 => text,          ; measurement description
}

psa-software-components = (
    psa-software-components-key => [ + psa-software-component ]
)
